//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssemblyChallanDeduction
    {
        public int AssemblyChallanDeductionId { get; set; }
        public Nullable<int> OutAssemblyId { get; set; }
        public Nullable<int> ChallanProductId { get; set; }
        public Nullable<int> OutQuantity { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
    
        public virtual ChallanProduct ChallanProduct { get; set; }
        public virtual OutAssembly OutAssembly { get; set; }
    }
}
