//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASFInvoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BASFInvoice()
        {
            this.InvoiceOutStocks = new HashSet<InvoiceOutStock>();
        }
    
        public int BASFInvoiceId { get; set; }
        public Nullable<int> BASFInvoiceNo { get; set; }
        public Nullable<System.DateTime> BASFInvoiceDate { get; set; }
        public Nullable<int> IsNg { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceOutStock> InvoiceOutStocks { get; set; }
    }
}
