//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChallanProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChallanProduct()
        {
            this.AccChallanDeductions = new HashSet<AccChallanDeduction>();
            this.AssemblyChallanDeductions = new HashSet<AssemblyChallanDeduction>();
            this.ChallanDeductions = new HashSet<ChallanDeduction>();
            this.InvoiceChallanDeductions = new HashSet<InvoiceChallanDeduction>();
        }
    
        public int ChallanProductId { get; set; }
        public Nullable<int> ChallanId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> InputQuantity { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccChallanDeduction> AccChallanDeductions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssemblyChallanDeduction> AssemblyChallanDeductions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChallanDeduction> ChallanDeductions { get; set; }
        public virtual ChallanDetail ChallanDetail { get; set; }
        public virtual ProductDetail ProductDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceChallanDeduction> InvoiceChallanDeductions { get; set; }
    }
}
