//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class erpdbEntities : DbContext
    {
        public erpdbEntities()
            : base("name=erpdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<InputCode> InputCodes { get; set; }
        public virtual DbSet<OutputCode> OutputCodes { get; set; }
        public virtual DbSet<PartType> PartTypes { get; set; }
    }
}
