//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class erpdbEntities : DbContext
    {
        public erpdbEntities()
            : base("name=erpdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccChallanDeduction> AccChallanDeductions { get; set; }
        public virtual DbSet<AccPODeduction> AccPODeductions { get; set; }
        public virtual DbSet<AssemblyChallanDeduction> AssemblyChallanDeductions { get; set; }
        public virtual DbSet<AssemblyPODeduction> AssemblyPODeductions { get; set; }
        public virtual DbSet<BASFInvoice> BASFInvoices { get; set; }
        public virtual DbSet<ChallanDeduction> ChallanDeductions { get; set; }
        public virtual DbSet<ChallanDetail> ChallanDetails { get; set; }
        public virtual DbSet<ChallanProduct> ChallanProducts { get; set; }
        public virtual DbSet<InvoiceChallanDeduction> InvoiceChallanDeductions { get; set; }
        public virtual DbSet<InvoiceOutStock> InvoiceOutStocks { get; set; }
        public virtual DbSet<OutAcc> OutAccs { get; set; }
        public virtual DbSet<OutAssembly> OutAssemblys { get; set; }
        public virtual DbSet<OutStock> OutStocks { get; set; }
        public virtual DbSet<PODeduction> PODeductions { get; set; }
        public virtual DbSet<PODetail> PODetails { get; set; }
        public virtual DbSet<POProduct> POProducts { get; set; }
        public virtual DbSet<ProductCategory> ProductCategorys { get; set; }
        public virtual DbSet<ProductDetail> ProductDetails { get; set; }
        public virtual DbSet<ProductMapping> ProductMappings { get; set; }
        public virtual DbSet<ProductType> ProductTypes { get; set; }
        public virtual DbSet<VendorChallan> VendorChallans { get; set; }
    }
}
