//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class InputCode
    {
        public int InputCodeId { get; set; }
        public string InputCodeNo { get; set; }
        public string InputMaterialDesc { get; set; }
        public int InputQuantity { get; set; }
        public int SplitQuantity { get; set; }
        public int PartTypeId { get; set; }
        public string BASFChallanNo { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public Nullable<int> OutputCodeId { get; set; }

        [JsonIgnore]
        public virtual OutputCode OutputCode { get; set; }
        [JsonIgnore]
        public virtual PartType PartType { get; set; }
    }
}
