//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class PODeduction
    {
        public int PODeductionId { get; set; }
        public Nullable<int> OutStockId { get; set; }
        public Nullable<int> POProductId { get; set; }
        public Nullable<int> OutQuantity { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
    
        public virtual OutStock OutStock { get; set; }
        public virtual POProduct POProduct { get; set; }
    }
}
