//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class POProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public POProduct()
        {
            this.AccPODeductions = new HashSet<AccPODeduction>();
            this.AssemblyPODeductions = new HashSet<AssemblyPODeduction>();
            this.PODeductions = new HashSet<PODeduction>();
        }
    
        public int POProductId { get; set; }
        public Nullable<int> POId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> InputQuantity { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccPODeduction> AccPODeductions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssemblyPODeduction> AssemblyPODeductions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PODeduction> PODeductions { get; set; }
        public virtual PODetail PODetail { get; set; }
        public virtual ProductDetail ProductDetail { get; set; }
    }
}
