//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductMapping
    {
        public int ProductMappingId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> MappingProductId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
    
        public virtual ProductDetail ProductDetail1 { get; set; }
        public virtual ProductDetail ProductDetail { get; set; }
    }
}
